### PR TITLE
Enh: Allow model edit and fix some of the initial installed models to have 1 button

### LINKED ISSUE #91: SCCP Advance Server Configuration: edit settings impossible
If you press the edit button you can't really edit anything so as a very unintuitive workaround you can add a new model with exactly the same values as the existing model, with the settings you want to change and only that overwrites the current settings.

Please fix this. Thanks

### PR DESCRIPTION
**Pull request by dkgroot**
Fix: Default models should have at least 1 button if number is currently no known

Enh: allow all model information to be edited.

Fixes: #91

### CODE REVIEW

**Comment by hboetes** [comment]
@dkgroot is de beste =)

I just tested this patch and it looks good. I can't see the effect since I'm at home, but I'll report back in the morning.

**Comment by dkgroot** [comment]
@hboetes Thanks for checking/testing. Hopefully Alex/PhantomVl will be around soon to merge it.

**Comment by hboetes** [comment]
Works like it should! Thanks!

**Comment by hboetes** [comment]
Accidentally closed. :-o

**Comment by dkgroot** [comment]
Has been replaced by #103

**Pull request closed without merging**
