### PR TITLE
Set of small corrections and added comments

### PR DESCRIPTION
**Pull request by dkgroot**
- Update README.md
- Commented out astman_retrieveJSFromMetaData in install.php (was moved to srvinterface)
- Addd/Updated some !TODO! entries
- Spelling:
  - devise -> device
  - Compatable/Comable -> Compatible
  - Templet -> Template
  - buton -> button
  - Templatee -> Template

### CODE REVIEW

**Comment by dkgroot** [comment]
Wow that was fast :-)

**Comment by NightShift21** [comment]
Whoops\Exception\ErrorException 
/var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php611

**Comment by NightShift21** [comment]
Whoops \ Exception \  ErrorException (E_PARSE)
syntax error, unexpected ')'
/
var
/
www
/
html
/
admin
/
modules
/
sccp_manager
/
Sccp_manager.class.php
611

________________________________

**Comment by dkgroot** [comment]
@NightShift21 
I think Alex already a couple of small correction to fix these, right ?

**Comment by PhantomVl** [comment]
As you are all fast ! I posted the interim version just for 5 minutes !!! So you get during this time a temporary version of the code to drag yourself ! :-)) I consciously thought that I would be easier to merge the code, then take him to my workplace to check and correct errors. Maybe it was an incorrect scenario.

**Pull request merged**
