### PR TITLE
When writing sccp.conf also check/create sccp_custom.conf 

### PR DESCRIPTION
**Pull request by dkgroot**
and include it into the main sccp.conf

References: #67

Signed-off-by: Diederik de Groot <dkgroot@talon.nl>

### CODE REVIEW

**Comment by dkgroot** [comment]
Note: Instead of creating sccp_custom.conf if it doesn't exist, we could also reverse the logic, and only add "#include sccp_custom.conf" if the file is found, if you like that better.

**Comment by Cynjut** [comment]
Plus 1Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Diederik de Groot <notifications@github.com> Date: 11/10/20  06:14  (GMT-06:00) To: PhantomVl/sccp_manager <sccp_manager@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [PhantomVl/sccp_manager] When writing sccp.conf also check/create sccp_custom.conf  (#87) 
Note: Instead of creating sccp_custom.conf if it doesn't exist, we could also reverse the logic, and only add "#include sccp_custom.conf" if the file is found, if you like that better.

**Comment by dkgroot** [comment]
@Cynjut Hi Dave, Long time no see :-)

**Comment by Cynjut** [comment]
I've been keeping an eye on you. 😁Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Diederik de Groot <notifications@github.com> Date: 11/10/20  08:48  (GMT-06:00) To: PhantomVl/sccp_manager <sccp_manager@noreply.github.com> Cc: Dave <burgess@cynjut.com>, Mention <mention@noreply.github.com> Subject: Re: [PhantomVl/sccp_manager] When writing sccp.conf also check/create sccp_custom.conf  (#87) 
@Cynjut Hi Dave, Long time no see :-)

**Pull request closed without merging**
