### PR TITLE
Switching asmanager: 'enabled' to 'off'

### LINKED ISSUE #106: Module issue after reinstall
Hello,

I am getting a strange PHP issue occurring when I navigate to the SCCP Phone Manager screen. There's a list of extensions that can be seen in the screen shot I've posted as well as the error above. If I delete the extensions, the come back right after I navigate away and come back to the screen. I recently had to reinstall FreePBX and had to restore from a prior config. I tried reinstalling SCCP and the module which didn't help. Not sure what I should do next. I'm using version 14.0.0.2M of the module. Asterisk 16.15.1, FreePBX 15.0.17.24. Thank you.
sccp issue

### PR DESCRIPTION
**Pull request by tensi0n519**
Not exactly sure what ;enabled; controls, but it seems to switch of some debug mode. I check the php-asmanager.php file but could not find what it does control.

Fixes: #106

### CODE REVIEW

**Comment by tensi0n519** [comment]
Partial revert of c929649 in which asmanager:'enabled' was turned on by @steve-lad.

**Comment by steve-lad** [comment]
This effectively disables the ami interface, which should only be necessary if the version of chan-sccp is not compatible. This has been fixed with a revised installer (not yet committed) that verifies chan-sccp compatibility. 

This pull should not be required.

**Comment by tensi0n519** [comment]
Hello Steve,

Thanks for responding and working on this incident. Diederik actually responded to my post and we were chatting about it on gitter. During our conversation, he offered to remote into my computer and take a look at the issue. He’s actually the one who made the suggested changes using my account which was logged in. That’s why it shows me as posting. Hopefully that makes sense.

Anyways did you still want me to respond to your last message with your requests? Let me know. 

Ryan

**Comment by steve-lad** [comment]
> Hello Steve, Thanks for responding and working on this incident. Diederik actually responded to my post and we were chatting about it on gitter. During our conversation, he offered to remote into my computer and take a look at the issue. He’s actually the one who made the suggested changes using my account which was logged in. That’s why it shows me as posting. Hopefully that makes sense. Anyways did you still want me to respond to your last message with your requests? Let me know. Ryan Sent from my mobile device.
> […](#)
> On Feb 22, 2021, at 04:50, steve-lad ***@***.***> wrote: ﻿ This effectively disables the ami interface, which should only be necessary if the version of chan-sccp is not compatible. This has been fixed with a revised installer (not yet committed) that verifies chan-sccp compatibility. This pull should not be required. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steve-lad** [comment]
Hi Ryan,

What revision of chan-sccp are you using - that's what is essential?

**Comment by tensi0n519** [comment]
I am using the latest version of chan-sccp. I did the installation yesterday using the latest. Is there a way to actually confirm the version? Let me know if you need me to do that and if you wouldn’t mind advising how to go about getting that info. Thank you.

 

-Ryan

**Comment by tensi0n519** [comment]
Hi Steve,

 

Reference to your last question….I figured it out. I attached the screenshot on github as well.

 

See attached.

 

-Ryan

**Comment by dkgroot** [comment]
Retracting this PR, steve informed me it was the wrong solution.

**Pull request closed without merging**
